#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           frontright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontleft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Motor6,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Motor7,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Motor8,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Motor9,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#pragma autonomousDuration(15)
#pragma userControlDuration(105)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  bStopTasksBetweenModes = true;

  bDisplayCompetitionStatusOnLcd = false;
}


float target = 0;
float initial = 0;

void setArmSpeed(int power) {
	motor[Motor6] = power;
	motor[Motor7] = power;
	motor[Motor8] = power;
	motor[Motor9] = power;
}

float getArm() {
	return initial - SensorValue[pot];
}

void calibrate() {
	while (true) {
		writeDebugStreamLine("%d", SensorValue[pot]);
		sleep(10);
	}
}

task armController()
{
	setArmSpeed(0);

	clearTimer(timer1);

	initial = SensorValue[pot];

	// constants in the PID control algorithm. Details are in:
	// https://en.wikipedia.org/wiki/PID_controller#Overview_of_methods
	float kp = 0.4, kd = 0.001;

	float e[2];    // e[0] current error, e[1] previous error

	e[0] = getArm() - target;
	writeDebugStreamLine("initial = %d", SensorValue[pot]);

	while (true) {
		wait1Msec(1);  // we update the motor 100x/s

		float dt = time1[timer1] / 1000.0;
		clearTimer(timer1);

		if (dt <= 0.001) dt = 0.001;

		// Update current and previous errors
		e[1] = e[0];
		e[0] = getArm() - target;

		// de is the derivative of the error, computed between
		// this step and the previous one
		float de = (e[0] - e[1]) / dt;

		// PID value is defined as follows:
		float power = kp * e[0] + kd * de;

		writeDebugStreamLine("angle=%d e=%f de=%f -> %f", SensorValue[pot], e[0], de, power);

		// The power must be kept between -127..+127
		if (power > 127.0) power = 127.0;
		if (power < -127.0) power = -127.0;

		setArmSpeed((int)power);
	}
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()

{
	motor[frontright] = -85;
	motor[backright] = -85;
	motor[frontleft] = -85;
	motor[backleft] = -85;

	wait1Msec(2000);

	motor[Motor6] = -85;
	motor[Motor7] = -85;
	motor[Motor8] = -85;
	motor[Motor9] = -85;
	wait1Msec(350);

	motor[Motor6] = -40;
	motor[Motor7] = -40;
	motor[Motor8] = -40;
	motor[Motor9] = -40;

		motor[frontright] = 85;
	motor[backright] = 85;
	motor[frontleft] = 85;
	motor[backleft] = 85;

	wait1Msec(800);

		motor[frontright] = -85;
	motor[backright] = -85;
	motor[frontleft] = -85;
	motor[backleft] = -85;
	wait1Msec(2000);

		motor[frontright] = 85;
	motor[backright] = 85;
	motor[frontleft] = 85;
	motor[backleft] = 85;
	wait1Msec(300);

	motor[frontright] = -85;
	motor[backright] = -85;
	motor[frontleft] = -85;
	motor[backleft] = -85;

	wait1Msec(1500);

		motor[frontright] = 85;
	motor[backright] = 85;
	motor[frontleft] = 85;
	motor[backleft] = 85;

	wait1Msec(500);

			motor[frontright] = 0;
	motor[backright] = 0;
	motor[frontleft] = 0;
	motor[backleft] = 0;
	wait1Msec(500);

	motor[Motor6] = -85;
	motor[Motor7] = -85;
	motor[Motor8] = -85;
	motor[Motor9] = -85;

	wait1Msec(1000);


	}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	target = 100;

  // User control code here, inside the loop
	// startTask(armController);

  clearTimer(timer2);

  while (true)
  {
  		motor[frontright] = -vexRT[Ch2];
    	motor[backright] = -vexRT[Ch2];

	    motor[frontleft] = -vexRT[Ch3];
	    motor[backleft] = -vexRT[Ch3];

	    setArmSpeed(-vexRT[Ch2Xmtr2] * 0.6);
      //if (time1[timer2] > 10) {
      //	int delta = ;
      //	if (abs(delta) > 10) {
      //   target += delta / 10;
      //  }
      //  clearTimer(timer2);
      //}
  }
}
